# Generated by Django 2.0.6 on 2018-08-22 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=100, verbose_name='接口名称')),
                ('apath', models.CharField(max_length=500, verbose_name='接口路径')),
                ('amethod', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], verbose_name='请求方式')),
                ('aheaders', models.CharField(blank=True, max_length=500, null=True, verbose_name='接口Headers信息')),
                ('aparams', models.TextField(max_length=5000, verbose_name='参数内容')),
                ('aresponse', models.TextField(verbose_name='参数返回')),
                ('astaus', models.IntegerField(choices=[(1, 'create'), (2, 'enable'), (3, 'update'), (4, 'disable')], verbose_name='接口状态')),
                ('add_time', models.DateField(blank=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '接口信息',
                'verbose_name': '接口信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateField(auto_created=True, blank=True, null=True, verbose_name='更新时间')),
                ('add_time', models.DateField(auto_created=True, blank=True, null=True, verbose_name='添加时间')),
                ('pname', models.CharField(max_length=100, verbose_name='项目名称')),
                ('pdesc', models.CharField(max_length=500, verbose_name='项目描述')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuser', to='users.User', verbose_name='创建者')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User', verbose_name='更新者')),
            ],
            options={
                'verbose_name_plural': '项目信息',
                'verbose_name': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, verbose_name='步骤名称')),
                ('spath', models.CharField(max_length=50, verbose_name='接口路径')),
                ('sdata', models.CharField(max_length=50, verbose_name='接口数据')),
                ('add_time', models.DateField(blank=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '测试步骤',
                'verbose_name': '测试步骤',
            },
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50, verbose_name='用例名称')),
                ('tdesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='用例描述')),
                ('tsteps', models.CharField(blank=True, max_length=100, null=True, verbose_name='用例步骤')),
                ('tstaus', models.IntegerField(choices=[(1, 'PASS'), (0, 'FAIL'), (2, 'STOP')], default=2, verbose_name='用例状态')),
                ('add_time', models.DateField(blank=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateField(blank=True, null=True, verbose_name='更新时间')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuser', to='users.User', verbose_name='创建者')),
                ('tapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ApiInfo', verbose_name='所属接口')),
                ('tproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name_plural': '用例信息',
                'verbose_name': '用例信息',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, verbose_name='版本')),
                ('add_time', models.DateField(blank=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '版本信息',
                'verbose_name': '版本信息',
            },
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='tversion',
            field=models.ForeignKey(on_delete=models.SET('1.0.0'), to='apitest.Version', verbose_name='测试用例版本'),
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User', verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='steps',
            name='stestcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.TestCaseInfo', verbose_name='所属用例'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='aproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ProjectInfo', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='aversion',
            field=models.ForeignKey(on_delete=models.SET('1.0.0'), to='apitest.Version', verbose_name='接口版本'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auser', to='users.User', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='pdate_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User', verbose_name='更新者'),
        ),
    ]
