# Generated by Django 2.0.6 on 2018-06-15 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=100, verbose_name='接口名称')),
                ('apath', models.CharField(max_length=50, verbose_name='接口路径')),
                ('aheaders', models.CharField(blank=True, max_length=100, null=True, verbose_name='接口Headers信息')),
                ('aparams', models.TextField(max_length=5000, verbose_name='参数内容')),
                ('aresponse', models.TextField(verbose_name='参数返回')),
                ('astaus', models.IntegerField(choices=[(1, 'create'), (2, 'enable'), (2, 'update'), (3, 'disable')], verbose_name='接口状态')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '接口信息',
                'verbose_name': '接口信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, verbose_name='项目名称')),
                ('pdesc', models.CharField(max_length=500, verbose_name='项目描述')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '项目信息',
                'verbose_name': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, verbose_name='步骤名称')),
                ('spath', models.CharField(max_length=50, verbose_name='接口路径')),
                ('sdata', models.CharField(max_length=50, verbose_name='接口数据')),
            ],
            options={
                'verbose_name_plural': '测试步骤',
                'verbose_name': '测试步骤',
            },
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50, verbose_name='用例名称')),
                ('tdesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='用例描述')),
                ('tsteps', models.CharField(max_length=100, verbose_name='用例步骤')),
                ('tstaus', models.IntegerField(choices=[(1, 'PASS'), (0, 'FAIL')], verbose_name='用例状态')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '用例信息',
                'verbose_name': '用例信息',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, verbose_name='版本')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '版本信息',
                'verbose_name': '版本信息',
            },
        ),
    ]
