# Generated by Django 2.0.6 on 2018-06-15 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinfo',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuser', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='tapi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ApiInfo', verbose_name='所属接口'),
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='tproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ProjectInfo', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='tversion',
            field=models.ForeignKey(on_delete=models.SET('1.0.0'), to='apitest.Version', verbose_name='测试用例版本'),
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='steps',
            name='stestcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.TestCaseInfo', verbose_name='所属用例'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuser', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='aproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ProjectInfo', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='aversion',
            field=models.ForeignKey(on_delete=models.SET('1.0.0'), to='apitest.Version', verbose_name='接口版本'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auser', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='pdate_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
    ]
