# Generated by Django 2.0.6 on 2018-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20180612_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='add_time',
            field=models.DateField(default=None, verbose_name='添加时间'),
        ),
    ]
