# Generated by Django 2.0.6 on 2018-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20180619_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='add_time',
            field=models.DateField(blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='add_time',
            field=models.DateField(blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='add_time',
            field=models.DateField(blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='tstaus',
            field=models.IntegerField(choices=[(1, 'PASS'), (0, 'FAIL'), (2, 'STOP')], default=2, verbose_name='用例状态'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='tsteps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用例步骤'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='version',
            name='add_time',
            field=models.DateField(blank=True, null=True, verbose_name='添加时间'),
        ),
    ]
