# Generated by Django 2.0.6 on 2018-06-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20180612_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name': '测试步骤', 'verbose_name_plural': '测试步骤'},
        ),
        migrations.RemoveField(
            model_name='steps',
            name='sstaus',
        ),
    ]
