# Generated by Django 2.0.6 on 2018-06-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_apiinfo_amethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='amethod',
            field=models.CharField(choices=[(1, 'GET'), (2, 'POST')], default='GET', max_length=10, verbose_name='请求方式'),
        ),
    ]
