# Generated by Django 2.0.6 on 2018-06-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20180625_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='amethod',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], verbose_name='请求方式'),
        ),
    ]
