# Generated by Django 2.0.6 on 2018-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20180625_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='aheaders',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='接口Headers信息'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='apath',
            field=models.CharField(max_length=500, verbose_name='接口路径'),
        ),
    ]
