# Generated by Django 2.0.6 on 2018-07-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20180625_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='add_time',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='update_time',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
